### ISSUE TITLE
_episodes now renamed to episodes in migration

### ISSUE THREAD

**Issue by cpranav93** [esciencecenter-digital-skills/carpentries-exercises-extractor#1]
The tool looks for _episodes for the folder containing episodes. The folder, atleast in deep learning, is now renamed episodes and this leads to an error with the tool for extracting exercises. 

Error:
'
github.com/carpentries-incubator/deep-learning-intro
Cloning https://github.com/carpentries-incubator/deep-learning-intro in temporary directory
Traceback (most recent call last):
  File "/home/cpranav93/mambaforge/bin/caex2", line 8, in <module>
    sys.exit(main())
  File "/home/cpranav93/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/cpranav93/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/cpranav93/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cpranav93/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/cpranav93/mambaforge/lib/python3.10/site-packages/caex2/extractor.py", line 85, in main
    episode_paths = get_episode_paths(repo_dir)
  File "/home/cpranav93/mambaforge/lib/python3.10/site-packages/caex2/extractor.py", line 64, in get_episode_paths
    episode_paths = sorted([path for path in episode_dir.iterdir() if path.name not in ['.gitkeep']])
  File "/home/cpranav93/mambaforge/lib/python3.10/site-packages/caex2/extractor.py", line 64, in <listcomp>
    episode_paths = sorted([path for path in episode_dir.iterdir() if path.name not in ['.gitkeep']])
  File "/home/cpranav93/mambaforge/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmptp3y9us1/repo/_episodes'
'

**Comment by svenvanderburg** [comment]
This was fixed with https://github.com/esciencecenter-digital-skills/carpentries-exercises-extractor/pull/3
